# ------------------------------------------------------------------
# One-time tool setup and configuration
# ------------------------------------------------------------------
[bootstrap.packages]
"apt:git"        = "latest"
"dnf:git"        = "latest"
"pacman:git"     = "latest"
"zypper:git"     = "latest"
"brew:git"       = "latest"
"scoop:git"      = "latest"
"winget:Git.Git" = "latest"

[env]
_.path = ["{{ config_root }}/bin"]

# ------------------------------------------------------------------
# Git Reset command shortcuts (via aliases/function as per shell)
# ------------------------------------------------------------------
### Bash / Zsh / Fish (Native [shell_alias] support)
[shell_alias]
gus       = "git reset HEAD"
grh       = "git reset"
grh!      = "git reset --hard"
gpristine = "git reset --hard && git clean -dfx"
### Powershell (Use hooks and funcs until [shell_alias] is supported)
[hooks.enter]
shell = "pwsh"
script = """
if (-not $global:__mise_func_registry) { $global:__mise_func_registry = @{} }
$__before = (Get-Command -CommandType Function).Name

function gus       { git reset HEAD @args }
function grh       { git reset @args }
function grh!      { git reset --hard @args }
function gpristine { git reset --hard && git clean -dfx @args }

# Save diff snapshot of function registry to get func names from this toml
$__new = (Get-Command -CommandType Function).Name | Where-Object { $__before -notcontains $_ }
$global:__mise_func_registry[(Get-Location).Path] = $__new
"""

# ------------------------------------------------------------------
# Undefine git command shortcuts (aliases/function as per shell)
# ------------------------------------------------------------------
### Powershell (Use hooks and undeclare funcs until [shell_alias] is supported)
[hooks.leave]
shell = "pwsh"
script = """
$key = (Get-Location).Path
# Use previously created diff-snapshot to get list of func names to unset/remove from registry
if ($global:__mise_func_registry -and $global:__mise_func_registry.ContainsKey($key)) {
	$global:__mise_func_registry[$key] | ForEach-Object { Remove-Item "function:$_" -Force }
	$global:__mise_func_registry.Remove($key)
}
"""
